import tkinter as tk
from tkinter import filedialog
from tkinter import scrolledtext
from PIL import ImageTk, Image

class Register_page(tk.Frame):
    def __init__(self, parent, controller):
        tk.Frame.__init__(self, parent, bg='#5cc9ed')
        self.controller = controller

        #Create elements & widgets
        self.space_label1 = tk.Label(self, height=8, width=50, bg='#5cc9ed')
        self.load_register_icon = tk.PhotoImage(file="images/register_hello.png")
        self.register_icon_label = tk.Label(self, image=self.load_register_icon, bg='#5cc9ed')
        self.register_label = tk.Label(self, text='Registration', font='Bahnschrift 70 bold', bg='#5cc9ed')
        #Backdrop Left
        self.load_backdrop1_img = Image.open("images/backdrop1.png")
        self.backdrop1 = ImageTk.PhotoImage(self.load_backdrop1_img.resize((450, 600), Image.ANTIALIAS))
        self.username_label = tk.Label(self, text='Username', font='Bahnschrift 32 bold', bg='#4C5270')
        self.username_entry = tk.Entry(self,font=('arial', 20), width=24)
        self.password_label = tk.Label(self, text='Password', font='Bahnschrift 32 bold', bg='#4C5270')
        self.password_entry = tk.Entry(self, font=('arial', 20), width=24)
        self.retype_password_label = tk.Label(self, text='Retype Password', font='Bahnschrift 32 bold', bg='#4C5270')
        self.retype_password_entry = tk.Entry(self, font=('arial', 20), width=24)
        self.email_label = tk.Label(self, text='Email', font='Bahnschrift 32 bold', bg='#4C5270')
        self.email_entry = tk.Entry(self, font=('arial', 20), width=24)
        #Backdrop Right
        self.backdrop2 = self.backdrop1
        self.backdrop1_label = tk.Label(self, image=self.backdrop1, bg='#5cc9ed')
        self.backdrop2_label = tk.Label(self, image=self.backdrop2, bg='#5cc9ed')
        self.proficient = tk.StringVar(self)
        self.proficient.set("Experience")  # default value
        self.experience1 = tk.OptionMenu(self, self.proficient, "<1Y", "1Y", "2Y", "3Y", ">3Y", "None")
        self.experience1.configure(font='Bahnschrift 12 bold', bg='#4c5270', fg='white', bd=-2)
        experience1_menu = self.nametowidget(self.experience1.menuname)
        experience1_menu.configure(font='Bahnschrift 12 bold')
        self.check1 = tk.Checkbutton(self, text='Python', font='Bahnschrift 16 bold', bg='#4c5270', bd=-2)
        self.experience2 = tk.OptionMenu(self, self.proficient, "<1Y", "1Y", "2Y", "3Y", ">3Y", "None")
        self.experience2.configure(font='Bahnschrift 12 bold', bg='#4c5270', fg='white', bd=-2)
        experience2_menu = self.nametowidget(self.experience2.menuname)
        experience2_menu.configure(font='Bahnschrift 12 bold')
        self.check2 = tk.Checkbutton(self, text='C++', font='Bahnschrift 16 bold', bg='#4c5270', bd=-2)
        self.experience3 = tk.OptionMenu(self, self.proficient, "<1Y", "1Y", "2Y", "3Y", ">3Y", "None")
        self.experience3.configure(font='Bahnschrift 12 bold', bg='#4c5270', fg='white', bd=-2)
        experience3_menu = self.nametowidget(self.experience3.menuname)
        experience3_menu.configure(font='Bahnschrift 12 bold')
        self.check3 = tk.Checkbutton(self, text='C#', font='Bahnschrift 16 bold', bg='#4c5270', bd=-2)
        self.experience4 = tk.OptionMenu(self, self.proficient, "<1Y", "1Y", "2Y", "3Y", ">3Y", "None")
        self.experience4.configure(font='Bahnschrift 12 bold', bg='#4c5270', fg='white', bd=-2)
        experience4_menu = self.nametowidget(self.experience4.menuname)
        experience4_menu.configure(font='Bahnschrift 12 bold')
        self.check4 = tk.Checkbutton(self, text='C', font='Bahnschrift 16 bold', bg='#4c5270', bd=-2)
        self.experience5 = tk.OptionMenu(self, self.proficient, "<1Y", "1Y", "2Y", "3Y", ">3Y", "None")
        self.experience5.configure(font='Bahnschrift 12 bold', bg='#4c5270', fg='white', bd=-2)
        experience5_menu = self.nametowidget(self.experience5.menuname)
        experience5_menu.configure(font='Bahnschrift 12 bold')
        self.check5 = tk.Checkbutton(self, text='Java', font='Bahnschrift 16 bold', bg='#4c5270', bd=-2)
        self.experience6 = tk.OptionMenu(self, self.proficient, "<1Y", "1Y", "2Y", "3Y", ">3Y", "None")
        self.experience6.configure(font='Bahnschrift 12 bold', bg='#4c5270', fg='white', bd=-2)
        experience6_menu = self.nametowidget(self.experience6.menuname)
        experience6_menu.configure(font='Bahnschrift 12 bold')
        self.check6 = tk.Checkbutton(self, text='Javascript', font='Bahnschrift 16 bold', bg='#4c5270', bd=-2)
        self.experience7 = tk.OptionMenu(self, self.proficient, "<1Y", "1Y", "2Y", "3Y", ">3Y", "None")
        self.experience7.configure(font='Bahnschrift 12 bold', bg='#4c5270', fg='white', bd=-2)
        experience7_menu = self.nametowidget(self.experience7.menuname)
        experience7_menu.configure(font='Bahnschrift 12 bold')
        self.check7 = tk.Checkbutton(self, text='PHP', font='Bahnschrift 16 bold', bg='#4c5270', bd=-2)
        self.experience8 = tk.OptionMenu(self, self.proficient, "<1Y", "1Y", "2Y", "3Y", ">3Y", "None")
        self.experience8.configure(font='Bahnschrift 12 bold', bg='#4c5270', fg='white', bd=-2)
        experience8_menu = self.nametowidget(self.experience8.menuname)
        experience8_menu.configure(font='Bahnschrift 12 bold')
        self.check8 = tk.Checkbutton(self, text='SQL', font='Bahnschrift 16 bold', bg='#4c5270', bd=-2)
        self.experience9 = tk.OptionMenu(self, self.proficient, "<1Y", "1Y", "2Y", "3Y", ">3Y", "None")
        self.experience9.configure(font='Bahnschrift 12 bold', bg='#4c5270', fg='white', bd=-2)
        experience9_menu = self.nametowidget(self.experience9.menuname)
        experience9_menu.configure(font='Bahnschrift 12 bold')
        self.check9 = tk.Checkbutton(self, text='HTML', font='Bahnschrift 16 bold', bg='#4c5270', bd=-2)
        self.experience10 = tk.OptionMenu(self, self.proficient, "<1Y", "1Y", "2Y", "3Y", ">3Y", "None")
        self.experience10.configure(font='Bahnschrift 12 bold', bg='#4c5270', fg='white', bd=-2)
        experience10_menu = self.nametowidget(self.experience10.menuname)
        experience10_menu.configure(font='Bahnschrift 12 bold')
        self.check10 = tk.Checkbutton(self, text='CSS', font='Bahnschrift 16 bold', bg='#4c5270', bd=-2)
        def goto_cfm_page():
            controller.show_frame('Register_confirmation_page')
        self.next_button = tk.Button(self, text='Continue To Next Step', font='Bahnschrift 20 bold', bg='#5cc9ed', bd=3, relief='raised', width=20, height=1, command=lambda: controller.show_frame('Register_confirmation_page'))

        #Arrange elements & widgets in grid
        self.register_icon_label.place(x=400, y=10)
        self.register_label.place(x=550, y=10)
        #Backdrop1
        self.backdrop1_label.place(x=250, y=175)
        self.username_label.place(x=375, y=200)
        self.username_label.tkraise()
        self.username_entry.place(x=295, y=270)
        self.username_entry.tkraise()
        self.password_label.place(x=375, y=330)
        self.password_label.tkraise()
        self.password_entry.place(x=295, y=400)
        self.password_entry.tkraise()
        self.retype_password_label.place(x=310, y=460)
        self.retype_password_label.tkraise()
        self.retype_password_entry.place(x=295, y=530)
        self.retype_password_entry.tkraise()
        self.email_label.place(x=420, y=580)
        self.email_label.tkraise()
        self.email_entry.place(x=295, y=650)
        self.email_entry.tkraise()
        #Backdrop2
        self.backdrop2_label.place(x=750, y=175)
        self.experience1.place(x=1000, y=230)
        self.check1.place(x=840, y=225)
        self.experience2.place(x=1000, y=270)
        self.check2.place(x=840, y=268)
        self.experience3.place(x=1000, y=310)
        self.check3.place(x=840, y=310)
        self.experience4.place(x=1000, y=350)
        self.check4.place(x=840, y=348)
        self.experience5.place(x=1000, y=390)
        self.check5.place(x=840, y=388)
        self.experience6.place(x=1000, y=430)
        self.check6.place(x=840, y=428)
        self.experience7.place(x=1000, y=470)
        self.check7.place(x=840, y=468)
        self.experience8.place(x=1000, y=510)
        self.check8.place(x=840, y=508)
        self.experience9.place(x=1000, y=550)
        self.check9.place(x=840, y=548)
        self.experience10.place(x=1000, y=590)
        self.check10.place(x=840, y=588)

        self.next_button.place(x=570, y=800)



